var resGame = {
	bg1_png: 'res/images/bg1.png',
	bg2_png: 'res/images/bg2.png',
	bg3_png: 'res/images/bg3.png',
	title_png: 'res/images/title.png',

	person1_png: 'res/images/person1.png',
	person2_png: 'res/images/person2.png',
	person3_png: 'res/images/person3.png',
	person4_png: 'res/images/person4.png',
	person5_png: 'res/images/person5.png',
	person6_png: 'res/images/person6.png',
	word1_png: 'res/images/word1.png',
	word2_png: 'res/images/word2.png',
	word3_png: 'res/images/word3.png',
	s1_1_png: 'res/images/s1_1.png',
	s1_2_png: 'res/images/s1_2.png',
	s1_3_png: 'res/images/s1_3.png',
	s1_4_png: 'res/images/s1_4.png',
	s1_5_png: 'res/images/s1_5.png',
	s1_6_png: 'res/images/s1_6.png',
	s1_7_png: 'res/images/s1_7.png',
	s1_8_png: 'res/images/s1_8.png',
	s1_9_png: 'res/images/s1_9.png',
	s1_10_png: 'res/images/s1_10.png',
	s1_11_png: 'res/images/s1_11.png',
	s2_1_png: 'res/images/s2_1.png',
	s2_2_png: 'res/images/s2_2.png',
	s2_3_png: 'res/images/s2_3.png',
	s2_4_png: 'res/images/s2_4.png',
	s2_5_png: 'res/images/s2_5.png',
	s2_6_png: 'res/images/s2_6.png',
	s2_7_png: 'res/images/s2_7.png',
	s2_8_png: 'res/images/s2_8.png',
	s3_1_png: 'res/images/s3_1.png',
	s3_2_png: 'res/images/s3_2.png',
	s3_3_png: 'res/images/s3_3.png',
	s3_4_png: 'res/images/s3_4.png',
	s3_5_png: 'res/images/s3_5.png',
	s3_6_png: 'res/images/s3_6.png',
	s3_7_png: 'res/images/s3_7.png',

	title_mp3: 'res/audios/title.mp3',
	intro_mp3: 'res/audios/intro.mp3',
	word_mp3: ['res/audios/man1.mp3','res/audios/man2.mp3','res/audios/man3.mp3','res/audios/woman1.mp3','res/audios/woman2.mp3','res/audios/woman3.mp3'],
	wrong_mp3: ['res/audios/manw.mp3','','','res/audios/womanw.mp3'],
	right_mp3: ['res/audios/manr1.mp3','res/audios/manr2.mp3','res/audios/manr3.mp3','res/audios/womanr1.mp3','res/audios/womanr2.mp3','res/audios/womanr3.mp3']
};

addModuleResourceByName(resGame);
